#!/bin/bash

function find-local-bin {
  local readonly prefix=$1; shift
  local bin_dir="$prefix-bin"
  local found_bin_dir=""

  current_dir=$(pwd)
  found_bin_dir=$current_dir/$bin_dir
  while [ ! -d $found_bin_dir ]; do
    current_dir=$(realpath "$current_dir/..")
    found_bin_dir=$current_dir/$bin_dir

    if [[ $current_dir == $HOME ]]; then
      found_bin_dir=$HOME/bin
      break
    fi
  done

  echo $found_bin_dir
}

_comma()
{
  local cur=${COMP_WORDS[COMP_CWORD]}

  local readonly dir=$(find-local-bin aet)

  cd $dir
  local bins=$(ls *)
  COMPREPLY=($(compgen -W "${bins}" -- "$dir/$cur"))
  return 0
}
complete -F _comma ,
