#!/usr/bin/env bash

zsh_path="$(command -v zsh)"
current_shell="$(getent passwd "$USER" | cut -d: -f7)"

if [ -n "$zsh_path" ] && [ "$current_shell" != "$zsh_path" ]; then
  echo Setting shell to zsh
  sudo chsh -s "$zsh_path" "$USER"
  echo Done setting shell to zsh
fi
