PERSONAL_BIN_PATH="$HOME/bin"

NODENV_PATH="$HOME/.nodenv/bin"
RBENV_PATH="$HOME/.rbenv/bin"

ZDOTDIR=$HOME/.config/zsh

[[ -d "$RBENV_PATH" ]] && PATH="$RBENV_PATH:$PATH"
[[ -d "$NODENV_PATH" ]] && PATH="$NODENV_PATH:$PATH"
[[ -d "$PERSONAL_BIN_PATH" ]] && PATH="$PERSONAL_BIN_PATH:$PATH"

# EDITOR
EDITOR=vim
GIT_EDITOR=vim
