NODENV_PATH="$HOME/.nodenv/bin"
PERSONAL_BIN="$HOME/bin"
RBENV_PATH="$HOME/.rbenv/bin"
ZDOTDIR=$HOME/.config/zsh

[[ -d "$RBENV_PATH" ]] && PATH="$RBENV_PATH:$PATH"
[[ -d "$NODENV_PATH" ]] && PATH="$NODENV_PATH:$PATH"
PATH="$PERSONAL_BIN:$PATH"

# EDITOR
EDITOR=vim
GIT_EDITOR=vim
